---
# Default values.
# Declare variables to be passed into your templates.
#
# Variables in `helm_deploy/values-[env].yaml` will take precedence.

generic-service:
  nameOverride: hmpps-manage-custody-mailbox-register-api
  productId: DPS030 # TODO: Update with correct product ID

  replicaCount: 2

  image:
    repository: ghcr.io/ministryofjustice/hmpps-manage-custody-mailbox-register-api
    tag: app_version # overridden at deployment time
    port: 8080

  ingress:
    enabled: true
    tlsSecretName: hmpps-manage-custody-mailbox-register-api-cert
    modsecurity_enabled: true
    modsecurity_snippet: |
      SecRuleEngine On
      SecDefaultAction "phase:2,pass,log,tag:github_team=mailbox-register-devs,tag:namespace={{ .Release.Namespace }}"
      # Default is only GET HEAD POST OPTIONS so need to include PUT etc.
      SecAction "id:900200,phase:1,nolog,pass,t:none,setvar:tx.allowed_methods=GET HEAD POST OPTIONS PUT DELETE,setvar:tx.paranoia_level=3"
      # Change default denial to be a 406 so that we can tell easily that it is modsecurity doing the blocking
      SecRuleUpdateActionById 949110 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecRuleUpdateActionById 959100 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      # Request Missing an Accept Header
      SecRuleRemoveById 920300
      # Request Missing User Agent Header
      SecRuleRemoveById 920320

  # https://github.com/ministryofjustice/hmpps-ip-allowlists/blob/main/ip-allowlist-groups.yaml
  allowlist:
    groups:
      - digital_staff_and_mojo
      - moj_cloud_platform

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%

  podSecurityContext:
    fsGroup: 2000

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]
  namespace_secrets:
    hmpps-manage-custody-mailbox-register-api-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    rds-instance-output:
      DB_NAME: "database_name"
      DB_PASS: "database_password"
      DB_USER: "database_username"
      DB_SERVER: "rds_instance_address"

generic-prometheus-alerts:
  targetApplication: hmpps-manage-custody-mailbox-register-api
  alertSeverity: moic
