package uk.gov.justice.digital.hmpps.mailboxregisterapi

enum class PrisonCode(val prisonName: String) {
  ACI("Altcourse (HMP)"),
  AGI("Askham Grange (HMP/YOI)"),
  ASI("Ashfield (HMP)"),
  AYI("Aylesbury (HMP)"),
  BAI("Belmarsh (HMP)"),
  BCI("Buckley Hall (HMP)"),
  BFI("Bedford (HMP)"),
  BLI("Bristol (HMP)"),
  BMI("Birmingham (HMP)"),
  BNI("Bullingdon (HMP)"),
  BRI("Bure (HMP)"),
  BSI("Brinsford (HMP)"),
  BWI("Berwyn (HMP)"),
  BXI("Brixton (HMP)"),
  BZI("Bronzefield (HMP)"),
  CDI("Chelmsford (HMP)"),
  CFI("Cardiff (HMP)"),
  CKI("Cookham Wood (HMP)"),
  CLI("Coldingley (HMP)"),
  CWI("Channings Wood (HMP)"),
  DAI("Dartmoor (HMP)"),
  DGI("Dovegate (HMP)"),
  DHI("Drake Hall (HMP/YOI)"),
  DMI("Durham (HMP)"),
  DNI("Doncaster (HMP)"),
  DTI("Deerbolt (HMP/YOI)"),
  DWI("Downview (HMP)"),
  EEI("Erlestoke (HMP)"),
  EHI("Standford Hill (HMP)"),
  ESI("East Sutton Park (HMP/YOI)"),
  EWI("Eastwood Park (HMP)"),
  EXI("Exeter (HMP)"),
  EYI("Elmley (HMP)"),
  FBI("Forest Bank (HMP/YOI)"),
  FDI("Ford (HMP)"),
  FEI("Fosse Way (HMP/YOI)"),
  FHI("Foston Hall (HMP)"),
  FKI("Frankland (HMP)"),
  FMI("Feltham (HMP/YOI)"),
  FNI("Full Sutton (HMP)"),
  FSI("Featherstone (HMP)"),
  FWI("Five Wells (FWI)"),
  GHI("Garth (HMP)"),
  GMI("Guys Marsh (HMP)"),
  GNI("Grendon (HMP)"),
  GTI("Gartree (HMP)"),
  HBI("Hollesley Bay (HMP)"),
  HCI("Huntercombe (HMP)"),
  HDI("Hatfield (HMP/YOI)"),
  HEI("Hewell (HMP)"),
  HHI("Holme House (HMP)"),
  HII("Hindley (HMP/YOI)"),
  HLI("Hull (HMP)"),
  HMI("Humber (HMP)"),
  HOI("High Down (HMP)"),
  HPI("Highpoint (HMP)"),
  HVI("Haverigg (HMP)"),
  ISI("Isis (HMP/YOI)"),
  IWI("Isle Of Wight (HMP)"),
  KMI("Kirkham (HMP)"),
  KVI("Kirklevington Grange (HMP)"),
  LCI("Leicester (HMP)"),
  LEI("Leeds (HMP)"),
  LFI("Lancaster Farms (HMP/YOI)"),
  LGI("Lowdham Grange (HMP)"),
  LHI("Lindholme (HMP)"),
  LII("Lincoln (HMP)"),
  LLI("Long Lartin (HMP)"),
  LNI("Low Newton(HMP)"),
  LPI("Liverpool (HMP)"),
  LTI("Littlehey (HMP)"),
  LWI("Lewes (HMP)"),
  LYI("Leyhill (HMP)"),
  MDI("Moorland (HMP/YOI)"),
  MHI("Morton Hall (HMP)"),
  MKI("Millsike (HMP)"),
  MRI("Manchester (HMP)"),
  MSI("Maidstone (HMP)"),
  MTI("The Mount (HMP)"),
  NHI("New Hall (HMP)"),
  NLI("Northumberland (HMP)"),
  NMI("Nottingham (HMP)"),
  NSI("North Sea Camp (HMP)"),
  NWI("Norwich (HMP/YOI)"),
  ONI("Onley (HMP)"),
  OWI("Oakwood (HMP)"),
  PBI("Peterborough (HMP)"),
  PDI("Portland (HMP/YOI)"),
  PFI("Peterborough Female (HMP)"),
  PNI("Preston (HMP)"),
  PRI("Parc (HMP)"),
  PVI("Pentonville (HMP)"),
  RCI("Rochester (HMP/YOI)"),
  RHI("Rye Hill (HMP)"),
  RNI("Ranby (HMP)"),
  RSI("Risley (HMP)"),
  SDI("Send (HMP)"),
  SFI("Stafford (HMP)"),
  SHI("Stoke Heath (HMP/YOI)"),
  SKI("Stocken (HMP)"),
  SLI("Swaleside (HMP)"),
  SNI("Swinfen Hall (HMP)"),
  SPI("Spring Hill (HMP)"),
  STI("Styal (HMP/YOI)"),
  SUI("Sudbury (HMP/YOI)"),
  SWI("Swansea (HMP)"),
  TCI("Thorn Cross (HMP/YOI)"),
  TSI("Thameside (HMP)"),
  UKI("Usk (HMP)"),
  UPI("Prescoed (HMP/YOI)"),
  VEI("The Verne (HMP)"),
  WCI("Winchester (HMP)"),
  WDI("Wakefield (HMP)"),
  WEI("Wealstun (HMP)"),
  WHI("Woodhill (HMP)"),
  WII("Warren Hill (HMP)"),
  WLI("Wayland (HMP)"),
  WMI("Wymott (HMP)"),
  WNI("Werrington (HMP/YOI)"),
  WRI("Whitemoor (HMP)"),
  WSI("Wormwood Scrubs (HMP)"),
  WTI("Whatton (HMP)"),
  WWI("Wandsworth (HMP)"),
  WYI("Wetherby (HMP/YOI)"),
}
