---
# Per environment values which override defaults in hmpps-manage-custody-mailbox-register-api/values.yaml

generic-service:
  ingress:
    host: manage-custody-mailbox-register-api.hmpps.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"

  postgresDatabaseRestore:
    enabled: true
    namespace_secrets:
      rds-instance-output:
        DB_NAME: "database_name"
        DB_USER: "database_username"
        DB_PASS: "database_password"
        DB_HOST: "rds_instance_address"
      rds-instance-output-preprod:
        DB_NAME_PREPROD: "database_name"
        DB_USER_PREPROD: "database_username"
        DB_PASS_PREPROD: "database_password"
        DB_HOST_PREPROD: "rds_instance_address"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: mpc-alerts-prod
  rdsAlertsDatabases:
    cloud-platform-203aeeeaa9d8ab4c: prod
